/// One selectable emoji plus lowercase [keywords] used for search.
class EmojiEntry {
  const EmojiEntry(this.emoji, this.keywords);
  final String emoji;
  final String keywords;
}

/// A named group of emojis shown as a section in the picker.
class EmojiCategory {
  const EmojiCategory(this.name, this.entries);
  final String name;
  final List<EmojiEntry> entries;
}

/// Curated emojis grouped for the picker. Stored on the model as a plain string.
const List<EmojiCategory> emojiCatalog = [
  EmojiCategory('Smileys', [
    EmojiEntry('😀', 'happy smile grin'),
    EmojiEntry('😄', 'happy joy smile'),
    EmojiEntry('😎', 'cool sunglasses'),
    EmojiEntry('🥳', 'party celebrate'),
    EmojiEntry('😴', 'sleep tired'),
    EmojiEntry('🤓', 'nerd study smart'),
    EmojiEntry('😇', 'angel good'),
    EmojiEntry('🤩', 'star excited wow'),
    EmojiEntry('🥰', 'love adore'),
    EmojiEntry('😂', 'laugh funny'),
    EmojiEntry('😉', 'wink'),
    EmojiEntry('💪', 'strong muscle flex'),
  ]),
  EmojiCategory('Activity', [
    EmojiEntry('🏃', 'run running'),
    EmojiEntry('🏋️', 'gym weights lift'),
    EmojiEntry('🧘', 'yoga meditate'),
    EmojiEntry('🚴', 'bike cycling'),
    EmojiEntry('🏊', 'swim swimming'),
    EmojiEntry('⚽', 'soccer football'),
    EmojiEntry('🏀', 'basketball'),
    EmojiEntry('🎾', 'tennis'),
    EmojiEntry('🎮', 'game gaming'),
    EmojiEntry('⛹️', 'basketball play'),
    EmojiEntry('🥊', 'boxing fight'),
    EmojiEntry('🤸', 'stretch gymnastics'),
  ]),
  EmojiCategory('Health', [
    EmojiEntry('❤️', 'heart love health'),
    EmojiEntry('💧', 'water hydrate'),
    EmojiEntry('🥗', 'salad healthy food'),
    EmojiEntry('💊', 'pills medicine'),
    EmojiEntry('🩺', 'doctor health checkup'),
    EmojiEntry('🧠', 'brain mind'),
    EmojiEntry('😴', 'sleep rest'),
    EmojiEntry('🚭', 'no smoking quit'),
    EmojiEntry('🦷', 'teeth dental'),
    EmojiEntry('🛌', 'sleep bed rest'),
    EmojiEntry('🧴', 'skincare lotion'),
    EmojiEntry('🩹', 'bandage heal'),
  ]),
  EmojiCategory('Study & Work', [
    EmojiEntry('📚', 'books study read'),
    EmojiEntry('✏️', 'write pencil note'),
    EmojiEntry('💻', 'laptop work code'),
    EmojiEntry('🎓', 'graduate school'),
    EmojiEntry('🔬', 'science lab'),
    EmojiEntry('🧮', 'math abacus'),
    EmojiEntry('📝', 'notes write journal'),
    EmojiEntry('💡', 'idea light'),
    EmojiEntry('🗂️', 'files organize'),
    EmojiEntry('📈', 'chart progress growth'),
    EmojiEntry('🖥️', 'computer work'),
    EmojiEntry('🌐', 'web internet language'),
  ]),
  EmojiCategory('Creative', [
    EmojiEntry('🎨', 'art paint'),
    EmojiEntry('🎵', 'music note song'),
    EmojiEntry('🎧', 'music headphones'),
    EmojiEntry('🎸', 'guitar music'),
    EmojiEntry('📷', 'camera photo'),
    EmojiEntry('🎬', 'movie film'),
    EmojiEntry('🎤', 'sing mic'),
    EmojiEntry('🎹', 'piano music'),
    EmojiEntry('🖌️', 'paint brush art'),
    EmojiEntry('🎭', 'theater drama'),
    EmojiEntry('📸', 'photo camera'),
    EmojiEntry('🪕', 'banjo music'),
  ]),
  EmojiCategory('Food & Drink', [
    EmojiEntry('🍎', 'apple fruit'),
    EmojiEntry('🍕', 'pizza food'),
    EmojiEntry('🍔', 'burger food'),
    EmojiEntry('🍜', 'noodles ramen'),
    EmojiEntry('🍣', 'sushi food'),
    EmojiEntry('🍰', 'cake dessert'),
    EmojiEntry('🥦', 'broccoli veg healthy'),
    EmojiEntry('🥚', 'egg breakfast'),
    EmojiEntry('☕', 'coffee drink'),
    EmojiEntry('🍵', 'tea drink'),
    EmojiEntry('🍺', 'beer drink'),
    EmojiEntry('🥤', 'drink soda'),
  ]),
  EmojiCategory('Nature', [
    EmojiEntry('🌱', 'plant grow seedling'),
    EmojiEntry('🌳', 'tree nature'),
    EmojiEntry('🌸', 'flower blossom'),
    EmojiEntry('☀️', 'sun sunny'),
    EmojiEntry('🌙', 'moon night'),
    EmojiEntry('⭐', 'star'),
    EmojiEntry('🔥', 'fire streak hot'),
    EmojiEntry('🌈', 'rainbow'),
    EmojiEntry('🍃', 'leaf nature'),
    EmojiEntry('🐶', 'dog pet'),
    EmojiEntry('🐱', 'cat pet'),
    EmojiEntry('🦋', 'butterfly'),
  ]),
  EmojiCategory('Travel', [
    EmojiEntry('✈️', 'plane travel fly'),
    EmojiEntry('🚗', 'car drive'),
    EmojiEntry('🚲', 'bike cycling'),
    EmojiEntry('🏠', 'home house'),
    EmojiEntry('🗺️', 'map travel'),
    EmojiEntry('🏖️', 'beach vacation'),
    EmojiEntry('⛰️', 'mountain hike'),
    EmojiEntry('🏝️', 'island beach'),
    EmojiEntry('🚀', 'rocket space'),
    EmojiEntry('⛺', 'camp tent'),
    EmojiEntry('🧭', 'compass explore'),
    EmojiEntry('🌍', 'earth world globe'),
  ]),
  EmojiCategory('Objects', [
    EmojiEntry('⏰', 'alarm time clock'),
    EmojiEntry('📱', 'phone mobile'),
    EmojiEntry('💰', 'money save'),
    EmojiEntry('🛒', 'shopping cart buy'),
    EmojiEntry('🔑', 'key'),
    EmojiEntry('✅', 'done check complete'),
    EmojiEntry('🎯', 'target goal aim'),
    EmojiEntry('🏆', 'trophy win goal'),
    EmojiEntry('🔔', 'bell reminder'),
    EmojiEntry('📅', 'calendar date'),
    EmojiEntry('❤️', 'heart love'),
    EmojiEntry('🪥', 'toothbrush teeth'),
  ]),
];
