// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4xyEJtWnObErbAS375ExjuI0Nkg1ljtg',
    appId: '1:713399210834:web:b74bab9a38315561afe08b',
    messagingSenderId: '713399210834',
    projectId: 'nokapp-habits',
    authDomain: 'nokapp-habits.firebaseapp.com',
    storageBucket: 'nokapp-habits.firebasestorage.app',
    measurementId: 'G-9ZDKL927W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfea7bvb9EEARGCTP-ZPsfajPwlhn9Hm4',
    appId: '1:713399210834:android:25dd1130e07634a5afe08b',
    messagingSenderId: '713399210834',
    projectId: 'nokapp-habits',
    storageBucket: 'nokapp-habits.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV-W6MYjRlB4Uq2HQBZuIZUrfzEePN-rQ',
    appId: '1:713399210834:ios:16980de99d4c8253afe08b',
    messagingSenderId: '713399210834',
    projectId: 'nokapp-habits',
    storageBucket: 'nokapp-habits.firebasestorage.app',
    iosBundleId: 'com.nokapp.habits',
  );
}
